/**
 * ============================================================
 *  BUNOFEED — Products & Campaign Data  (products.js)
 *  Auto-generated by Bunofeed Admin Panel
 *  Last updated: 9/5/2026, 5:59:55 pm
 * ============================================================
 */

window.BUNOFEED_DATA = {
  "payment": {
    "razorpayKeyId": "rzp_live_SmuiE4hy1NjJLM",
    "currency": "INR",
    "businessName": "Bunofeed",
    "description": "Healthy Natural Foods",
    "logoUrl": "https://i.ibb.co/5W7myd6t/Brand-logo-2.png",
    "themeColor": "#ff6b00"
  },
  "campaign": {
    "active": false,
    "text": "🎉 Launch Special — Free shipping on orders above ₹499!",
    "link": "shop.html",
    "linkText": "Shop Now →",
    "bgColor": "#ff6b00",
    "textColor": "#ffffff",
    "expiryDate": "2026-06-30"
  },
  "sale": {
    "active": false,
    "discountPercent": 15,
    "label": "SALE",
    "endDate": "2026-05-31"
  },
  "shipping": {
    "freeShippingAbove": 499,
    "shippingCharge": 0
  },
  "products": [
    {
      "id": "creamy-pb",
      "name": "Dark Chocolate Peanut Butter Crunchy",
      "tagline": "Tasty, Crunchy & packed with protein.",
      "description": "Indulgent dark chocolate meets creamy roasted peanuts in a perfectly smooth spread crafted for taste and nutrition. Made with high-quality peanuts and rich cocoa, this protein-packed peanut butter delivers a deep chocolate flavor without compromising on wholesome ingredients.\nPerfect for:\n\n\nToasts & sandwiches\n\n\nSmoothies & shakes\n\n\nFruits & pancakes\n\n\nPre/post-workout meals\n\n\nStraight-from-the-jar cravings\n\n\nWhy you’ll love it:\n\n\nSmooth & creamy texture\n\n\nRich dark chocolate flavor\n\n\nGood source of plant-based protein\n\nEnergy-boosting healthy fats\n\n\nGreat for fitness & healthy snacking",
      "price": 1,
      "weight": "400g",
      "image": "https://i.ibb.co/psxqc3J/1-removebg-preview.png",
      "images": [
        "https://i.ibb.co/psxqc3J/1-removebg-preview.png",
        "https://i.ibb.co/SDG4SYSN/1.png"
      ],
      "emoji": "🥜",
      "badge": "Best Seller",
      "badgeType": "bestseller",
      "bgClass": "peanut-bg",
      "category": "peanut-butter",
      "features": [
        "High Protein",
        "No Palm Oil",
        "Vegan"
      ],
      "ingredients": "Roasted Peanuts (95%), Dark Cocoa Powder (4%), Salt (1%). No added sugar, no palm oil, no preservatives.",
      "storageInfo": "Store in a cool, dry place away from direct sunlight. Keep lid tightly closed after opening. Best consumed within 3 months of opening. No refrigeration required.",
      "keyBenefits": "Rich source of plant-based protein • Contains healthy monounsaturated fats • No palm oil or artificial preservatives • Antioxidant-rich dark cocoa • Suitable for pre/post-workout nutrition",
      "visible": true,
      "bestSeller": true
    },
    {
      "id": "choco-pb",
      "name": "Chocolate Peanut Butter",
      "tagline": "Guilt-free chocolate indulgence.",
      "description": "Dark cocoa meets rich peanut butter for a treat you can feel good about. No refined sugar, no palm oil. Great as a spread, dip, or protein shake mix-in.",
      "price": 329,
      "weight": "500g",
      "badge": null,
      "badgeType": null,
      "bestSeller": true,
      "image": "",
      "emoji": "🍫",
      "bgClass": "choco-bg",
      "features": [
        "Dark Cocoa",
        "No Palm Oil",
        "High Protein",
        "No Refined Sugar"
      ],
      "ingredients": "Roasted Peanuts (93%), Dark Cocoa Powder (5%), Himalayan Pink Salt (2%). No refined sugar, no palm oil, no artificial flavours.",
      "storageInfo": "Store in a cool, dry place. Keep lid tightly closed after use. Consume within 3 months of opening. No refrigeration needed.",
      "keyBenefits": "High in plant-based protein • Rich dark chocolate flavour without refined sugar • No palm oil • Healthy fats for sustained energy • Great for smoothies and baking",
      "category": "peanut-butter",
      "visible": true
    },
    {
      "id": "rolled-oats",
      "name": "Rolled Oats",
      "tagline": "Wholesome oats, heart-healthy goodness.",
      "description": "Quick-cooking whole grain rolled oats. Naturally high in beta-glucan fibre which supports heart health. Ideal for porridge, overnight oats, granola bars, and baking.",
      "price": 199,
      "weight": "1kg",
      "badge": "New",
      "badgeType": "new",
      "bestSeller": false,
      "image": "",
      "emoji": "🌾",
      "bgClass": "oat-bg",
      "features": [
        "Whole Grain",
        "High Fibre",
        "Heart Healthy",
        "No Preservatives"
      ],
      "ingredients": "100% Whole Grain Rolled Oats. No added sugar, no salt, no preservatives, no artificial flavours.",
      "storageInfo": "Store in a cool, dry, airtight container. Keep away from moisture. Best consumed within 12 months of manufacturing date once opened.",
      "keyBenefits": "High in beta-glucan fibre for heart health • Naturally gluten-free grain (check for cross-contamination) • Slow-release carbohydrates for sustained energy • Supports healthy cholesterol levels • Versatile for porridge, baking, and granola",
      "category": "oats",
      "visible": true
    },
    {
      "id": "crunchy-muesli",
      "name": "Crunchy Muesli",
      "tagline": "Your perfect power-packed breakfast.",
      "description": "A premium blend of rolled oats, mixed nuts, seeds, and real dried fruits. Loaded with fibre, healthy fats, and natural energy. No artificial flavours or added sugar.",
      "price": 349,
      "weight": "500g",
      "badge": null,
      "badgeType": null,
      "bestSeller": false,
      "image": "",
      "emoji": "🥣",
      "bgClass": "muesli-bg",
      "features": [
        "Mixed Nuts",
        "Dried Fruits",
        "No Added Sugar",
        "High Fibre"
      ],
      "ingredients": "Rolled Oats (55%), Mixed Nuts (Almonds, Cashews, Walnuts) (18%), Dried Fruits (Raisins, Cranberries) (15%), Seeds (Sunflower, Pumpkin) (10%), Cinnamon (2%). No added sugar, no artificial flavours, no preservatives.",
      "storageInfo": "Store in a cool, dry place in an airtight container. Avoid humidity. Best consumed within 6 months of opening. Do not refrigerate.",
      "keyBenefits": "Loaded with dietary fibre for gut health • Natural sugars from real dried fruits only • Healthy fats from mixed nuts and seeds • Rich in vitamins and minerals • Ideal as a breakfast with milk or yoghurt",
      "category": "muesli",
      "visible": true
    }
  ],
  "hero": {
    "subtitle": "Welcome to Bunofeed",
    "title": "Companion in your",
    "titleHighlight": "Healthy Lifestyle",
    "description": "Fuel your body with nature's finest — real, healthy food products. No nasties. Just goodness.",
    "image": "",
    "ctaText": "Shop Now",
    "ctaLink": "shop.html"
  },
  "brand": {
    "email": "bunofeedhelpdesk@gmail.com",
    "feedbackFormUrl": "https://docs.google.com/forms/d/e/1FAIpQLSejJAsyZq1snX9gEJr6CTpcVYwEopd34RsTf_pbYvgwz0WFDg/viewform?usp=header",
    "instagram": "https://www.instagram.com",
    "facebook": "https://www.facebook.com",
    "youtube": "https://www.youtube.com",
    "twitter": "https://www.x.com",
    "linkedin": "https://www.linkedin.com/in/akash-kumar-995739293"
  },
  "categories": [
    {
      "name": "Peanut Butter",
      "slug": "peanut-butter"
    },
    {
      "name": "Oats",
      "slug": "oats"
    },
    {
      "name": "Muesli",
      "slug": "muesli"
    },
    {
      "name": "Other",
      "slug": "other"
    }
  ]
};
